export { default as About } from "./About"
export { default as Adress } from "./Address"
export { default as Amenities } from "./Amenities"
export { default as Bookmark } from "./Bookmark"
export { default as Extras } from "./Extras"
export { default as Header } from "./Header"
export { default as Stats } from "./Stats"
